import { createFileRoute } from '@tanstack/react-router'
import { useState } from 'react'
import { Moon, Save } from 'lucide-react'
import { getAppearanceSettings, saveAppearanceSettings } from '../../server/admin.functions'

export const Route = createFileRoute('/admin/_authed/settings')({ loader: () => getAppearanceSettings(), component: AdminSettings })
function AdminSettings() {
  const initial = Route.useLoaderData(); const [enabled, setEnabled] = useState(initial.darkModeEnabled); const [saved, setSaved] = useState(false)
  return <div className="max-w-2xl"><p className="text-sm font-semibold text-amber-700">Paramètres · Apparence</p><h1 className="text-3xl font-bold tracking-tight">Mode sombre</h1><section className="mt-6 rounded-2xl border border-stone-200 bg-white p-5 sm:p-6"><div className="flex items-start gap-4"><div className="rounded-2xl bg-stone-950 p-3 text-white"><Moon className="h-5 w-5" /></div><div><h2 className="font-bold">Disponibilité du mode sombre</h2><p className="mt-1 text-sm leading-6 text-stone-500">Quand cette option est désactivée, aucun utilisateur ne voit de sélecteur de thème et l'application reste en mode clair.</p></div></div><div className="mt-6 grid grid-cols-2 gap-3"><button type="button" onClick={() => { setEnabled(true); setSaved(false) }} className={`min-h-12 rounded-xl border font-bold ${enabled ? 'border-stone-950 bg-stone-950 text-white' : 'border-stone-300'}`}>Activé</button><button type="button" onClick={() => { setEnabled(false); setSaved(false) }} className={`min-h-12 rounded-xl border font-bold ${!enabled ? 'border-stone-950 bg-stone-950 text-white' : 'border-stone-300'}`}>Désactivé</button></div><button type="button" onClick={async () => { await saveAppearanceSettings({ data: { darkModeEnabled: enabled } }); if (!enabled) { document.documentElement.classList.remove('dark'); localStorage.removeItem('nreservi-theme') }; setSaved(true) }} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-amber-600 px-4 font-bold text-white"><Save className="h-4 w-4" /> Enregistrer</button>{saved && <p className="mt-3 text-sm font-semibold text-emerald-700">Paramètre enregistré. Rechargez la page pour actualiser les menus.</p>}</section></div>
}
