import { createFileRoute } from '@tanstack/react-router'
import { useState } from 'react'
import { CalendarPlus, Clock3, History, Pencil, X } from 'lucide-react'
import { createSubscription, getSubscriptions, updateSubscription } from '../../server/admin.functions'

export const Route = createFileRoute('/admin/_authed/subscriptions')({ loader: () => getSubscriptions(), component: SubscriptionsPage })

const STATUS = {
  active: { label: 'Active', className: 'bg-emerald-100 text-emerald-800' },
  expiring_soon: { label: 'Expire bientôt', className: 'bg-amber-100 text-amber-800' },
  expired: { label: 'Expirée', className: 'bg-red-100 text-red-700' },
  suspended: { label: 'Suspendue', className: 'bg-stone-200 text-stone-700' },
} as const

function SubscriptionsPage() {
  const [rows, setRows] = useState<any[]>(Route.useLoaderData() as any[])
  const [editing, setEditing] = useState<any | null>(null)
  const [renewing, setRenewing] = useState<any | null>(null)
  const [history, setHistory] = useState<any | null>(null)
  async function refresh() { setRows(await getSubscriptions()) }
  return <div><div><p className="text-sm font-semibold text-amber-700">Administration</p><h1 className="text-3xl font-bold tracking-tight text-stone-950">Abonnements</h1><p className="mt-2 text-sm text-stone-500">L'accès propriétaire est validé côté serveur selon les dates ci-dessous.</p></div><div className="mt-6 grid gap-4">{rows.map((row) => { const status = STATUS[row.status as keyof typeof STATUS]; return <article key={row.restaurant.id} className="rounded-2xl border border-stone-200 bg-white p-4 sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-bold">{row.restaurant.name}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${status.className}`}>{status.label}</span></div>{row.current ? <p className="mt-2 text-sm text-stone-500">Début : <strong>{formatDate(row.current.startDate)}</strong> · Fin : <strong>{formatDate(row.current.endDate)}</strong></p> : <p className="mt-2 text-sm text-red-600">Aucun abonnement configuré.</p>}<p className="mt-1 text-sm font-semibold text-stone-600">{row.active && row.daysRemaining !== null ? `${row.daysRemaining} jour(s) restant(s)` : 'Abonnement expiré — accès suspendu'}</p></div><div className="grid grid-cols-3 gap-2"><button onClick={() => setRenewing(row)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-stone-950 px-3 text-xs font-bold text-white"><CalendarPlus className="h-4 w-4" /> Renouveler</button><button disabled={!row.current} onClick={() => setEditing({ ...row.current, restaurantName: row.restaurant.name })} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-stone-300 px-3 text-xs font-bold disabled:opacity-40"><Pencil className="h-4 w-4" /> Modifier</button><button onClick={() => setHistory(row)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-stone-300 px-3 text-xs font-bold"><History className="h-4 w-4" /> Historique</button></div></div></article> })}</div>{renewing && <PeriodModal title={`Renouveler · ${renewing.restaurant.name}`} initialStart={nextDay(renewing.current?.endDate)} initialEnd="" onClose={() => setRenewing(null)} onSubmit={async (startDate, endDate) => { await createSubscription({ data: { restaurantId: renewing.restaurant.id, startDate, endDate } }); setRenewing(null); refresh() }} />}{editing && <PeriodModal title={`Modifier · ${editing.restaurantName}`} initialStart={editing.startDate} initialEnd={editing.endDate} onClose={() => setEditing(null)} onSubmit={async (startDate, endDate) => { await updateSubscription({ data: { id: editing.id, startDate, endDate } }); setEditing(null); refresh() }} />}{history && <HistoryModal row={history} onClose={() => setHistory(null)} />}</div>
}

function PeriodModal({ title, initialStart, initialEnd, onClose, onSubmit }: { title: string; initialStart: string; initialEnd: string; onClose: () => void; onSubmit: (start: string, end: string) => Promise<void> }) {
  const [startDate, setStartDate] = useState(initialStart); const [endDate, setEndDate] = useState(initialEnd); const [error, setError] = useState('')
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/45 sm:items-center sm:p-4"><form onSubmit={async (event) => { event.preventDefault(); if (!startDate || !endDate || endDate < startDate) return setError('Vérifiez les dates.'); await onSubmit(startDate, endDate) }} className="w-full max-w-md rounded-t-3xl bg-white p-5 sm:rounded-3xl sm:p-6"><div className="flex items-center justify-between"><h2 className="font-bold">{title}</h2><button type="button" onClick={onClose} className="p-2"><X className="h-5 w-5" /></button></div><div className="mt-5 grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Date de début<input required type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-stone-300 px-2 font-normal" /></label><label className="text-sm font-semibold">Date de fin<input required type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-stone-300 px-2 font-normal" /></label></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<button className="mt-5 min-h-11 w-full rounded-xl bg-stone-950 font-bold text-white">Enregistrer la période</button></form></div>
}

function HistoryModal({ row, onClose }: { row: any; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/45 sm:items-center sm:p-4"><section className="max-h-[85vh] w-full max-w-lg overflow-y-auto rounded-t-3xl bg-white p-5 sm:rounded-3xl sm:p-6"><div className="flex items-center justify-between"><h2 className="font-bold">Historique · {row.restaurant.name}</h2><button onClick={onClose} className="p-2"><X className="h-5 w-5" /></button></div><div className="mt-5 space-y-3">{row.history.map((period: any) => <div key={period.id} className="flex items-center gap-3 rounded-xl bg-stone-50 p-3"><Clock3 className="h-4 w-4 text-stone-400" /><p className="text-sm"><strong>{formatDate(period.startDate)}</strong> → <strong>{formatDate(period.endDate)}</strong></p></div>)}{!row.history.length && <p className="text-sm text-stone-400">Aucun historique.</p>}</div></section></div> }
function formatDate(value: string) { return new Date(`${value}T00:00:00`).toLocaleDateString('fr-DZ') }
function nextDay(value?: string) { const date = value ? new Date(`${value}T00:00:00Z`) : new Date(); date.setUTCDate(date.getUTCDate() + (value ? 1 : 0)); return date.toISOString().slice(0, 10) }
