/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyReservationsRouteImport } from './routes/my-reservations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsSlugRouteImport } from './routes/restaurants.$slug'
import { Route as OwnerLoginRouteImport } from './routes/owner/login'
import { Route as OwnerAuthedRouteImport } from './routes/owner/_authed'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthedRouteImport } from './routes/admin/_authed'
import { Route as OwnerAuthedIndexRouteImport } from './routes/owner/_authed.index'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin/_authed.index'
import { Route as OwnerAuthedSettingsRouteImport } from './routes/owner/_authed.settings'
import { Route as OwnerAuthedMenuRouteImport } from './routes/owner/_authed.menu'
import { Route as OwnerAuthedMarketingRouteImport } from './routes/owner/_authed.marketing'
import { Route as OwnerAuthedAnalyticsRouteImport } from './routes/owner/_authed.analytics'
import { Route as AdminAuthedSubscriptionsRouteImport } from './routes/admin/_authed.subscriptions'
import { Route as AdminAuthedSettingsRouteImport } from './routes/admin/_authed.settings'
import { Route as AdminAuthedOnboardRouteImport } from './routes/admin/_authed.onboard'
import { Route as OwnerAuthedSettingsWhatsappRouteImport } from './routes/owner/_authed.settings_.whatsapp'

const MyReservationsRoute = MyReservationsRouteImport.update({
  id: '/my-reservations',
  path: '/my-reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsSlugRoute = RestaurantsSlugRouteImport.update({
  id: '/restaurants/$slug',
  path: '/restaurants/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner/login',
  path: '/owner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAuthedRoute = OwnerAuthedRouteImport.update({
  id: '/owner/_authed',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAuthedIndexRoute = OwnerAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerAuthedRoute,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const OwnerAuthedSettingsRoute = OwnerAuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerAuthedRoute,
} as any)
const OwnerAuthedMenuRoute = OwnerAuthedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => OwnerAuthedRoute,
} as any)
const OwnerAuthedMarketingRoute = OwnerAuthedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => OwnerAuthedRoute,
} as any)
const OwnerAuthedAnalyticsRoute = OwnerAuthedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OwnerAuthedRoute,
} as any)
const AdminAuthedSubscriptionsRoute =
  AdminAuthedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AdminAuthedRoute,
  } as any)
const AdminAuthedSettingsRoute = AdminAuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedOnboardRoute = AdminAuthedOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const OwnerAuthedSettingsWhatsappRoute =
  OwnerAuthedSettingsWhatsappRouteImport.update({
    id: '/settings_/whatsapp',
    path: '/settings/whatsapp',
    getParentRoute: () => OwnerAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-reservations': typeof MyReservationsRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/owner': typeof OwnerAuthedRouteWithChildren
  '/owner/login': typeof OwnerLoginRoute
  '/restaurants/$slug': typeof RestaurantsSlugRoute
  '/admin/onboard': typeof AdminAuthedOnboardRoute
  '/admin/settings': typeof AdminAuthedSettingsRoute
  '/admin/subscriptions': typeof AdminAuthedSubscriptionsRoute
  '/owner/analytics': typeof OwnerAuthedAnalyticsRoute
  '/owner/marketing': typeof OwnerAuthedMarketingRoute
  '/owner/menu': typeof OwnerAuthedMenuRoute
  '/owner/settings': typeof OwnerAuthedSettingsRoute
  '/admin/': typeof AdminAuthedIndexRoute
  '/owner/': typeof OwnerAuthedIndexRoute
  '/owner/settings/whatsapp': typeof OwnerAuthedSettingsWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-reservations': typeof MyReservationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/owner/login': typeof OwnerLoginRoute
  '/restaurants/$slug': typeof RestaurantsSlugRoute
  '/admin/onboard': typeof AdminAuthedOnboardRoute
  '/admin/settings': typeof AdminAuthedSettingsRoute
  '/admin/subscriptions': typeof AdminAuthedSubscriptionsRoute
  '/owner/analytics': typeof OwnerAuthedAnalyticsRoute
  '/owner/marketing': typeof OwnerAuthedMarketingRoute
  '/owner/menu': typeof OwnerAuthedMenuRoute
  '/owner/settings': typeof OwnerAuthedSettingsRoute
  '/admin': typeof AdminAuthedIndexRoute
  '/owner': typeof OwnerAuthedIndexRoute
  '/owner/settings/whatsapp': typeof OwnerAuthedSettingsWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-reservations': typeof MyReservationsRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/owner/_authed': typeof OwnerAuthedRouteWithChildren
  '/owner/login': typeof OwnerLoginRoute
  '/restaurants/$slug': typeof RestaurantsSlugRoute
  '/admin/_authed/onboard': typeof AdminAuthedOnboardRoute
  '/admin/_authed/settings': typeof AdminAuthedSettingsRoute
  '/admin/_authed/subscriptions': typeof AdminAuthedSubscriptionsRoute
  '/owner/_authed/analytics': typeof OwnerAuthedAnalyticsRoute
  '/owner/_authed/marketing': typeof OwnerAuthedMarketingRoute
  '/owner/_authed/menu': typeof OwnerAuthedMenuRoute
  '/owner/_authed/settings': typeof OwnerAuthedSettingsRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
  '/owner/_authed/': typeof OwnerAuthedIndexRoute
  '/owner/_authed/settings_/whatsapp': typeof OwnerAuthedSettingsWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-reservations'
    | '/admin'
    | '/admin/login'
    | '/owner'
    | '/owner/login'
    | '/restaurants/$slug'
    | '/admin/onboard'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/owner/analytics'
    | '/owner/marketing'
    | '/owner/menu'
    | '/owner/settings'
    | '/admin/'
    | '/owner/'
    | '/owner/settings/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-reservations'
    | '/admin/login'
    | '/owner/login'
    | '/restaurants/$slug'
    | '/admin/onboard'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/owner/analytics'
    | '/owner/marketing'
    | '/owner/menu'
    | '/owner/settings'
    | '/admin'
    | '/owner'
    | '/owner/settings/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/my-reservations'
    | '/admin/_authed'
    | '/admin/login'
    | '/owner/_authed'
    | '/owner/login'
    | '/restaurants/$slug'
    | '/admin/_authed/onboard'
    | '/admin/_authed/settings'
    | '/admin/_authed/subscriptions'
    | '/owner/_authed/analytics'
    | '/owner/_authed/marketing'
    | '/owner/_authed/menu'
    | '/owner/_authed/settings'
    | '/admin/_authed/'
    | '/owner/_authed/'
    | '/owner/_authed/settings_/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyReservationsRoute: typeof MyReservationsRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  OwnerAuthedRoute: typeof OwnerAuthedRouteWithChildren
  OwnerLoginRoute: typeof OwnerLoginRoute
  RestaurantsSlugRoute: typeof RestaurantsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-reservations': {
      id: '/my-reservations'
      path: '/my-reservations'
      fullPath: '/my-reservations'
      preLoaderRoute: typeof MyReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$slug': {
      id: '/restaurants/$slug'
      path: '/restaurants/$slug'
      fullPath: '/restaurants/$slug'
      preLoaderRoute: typeof RestaurantsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/login': {
      id: '/owner/login'
      path: '/owner/login'
      fullPath: '/owner/login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/_authed': {
      id: '/owner/_authed'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/_authed/': {
      id: '/owner/_authed/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerAuthedIndexRouteImport
      parentRoute: typeof OwnerAuthedRoute
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/owner/_authed/settings': {
      id: '/owner/_authed/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerAuthedSettingsRouteImport
      parentRoute: typeof OwnerAuthedRoute
    }
    '/owner/_authed/menu': {
      id: '/owner/_authed/menu'
      path: '/menu'
      fullPath: '/owner/menu'
      preLoaderRoute: typeof OwnerAuthedMenuRouteImport
      parentRoute: typeof OwnerAuthedRoute
    }
    '/owner/_authed/marketing': {
      id: '/owner/_authed/marketing'
      path: '/marketing'
      fullPath: '/owner/marketing'
      preLoaderRoute: typeof OwnerAuthedMarketingRouteImport
      parentRoute: typeof OwnerAuthedRoute
    }
    '/owner/_authed/analytics': {
      id: '/owner/_authed/analytics'
      path: '/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof OwnerAuthedAnalyticsRouteImport
      parentRoute: typeof OwnerAuthedRoute
    }
    '/admin/_authed/subscriptions': {
      id: '/admin/_authed/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminAuthedSubscriptionsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/settings': {
      id: '/admin/_authed/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthedSettingsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/onboard': {
      id: '/admin/_authed/onboard'
      path: '/onboard'
      fullPath: '/admin/onboard'
      preLoaderRoute: typeof AdminAuthedOnboardRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/owner/_authed/settings_/whatsapp': {
      id: '/owner/_authed/settings_/whatsapp'
      path: '/settings/whatsapp'
      fullPath: '/owner/settings/whatsapp'
      preLoaderRoute: typeof OwnerAuthedSettingsWhatsappRouteImport
      parentRoute: typeof OwnerAuthedRoute
    }
  }
}

interface AdminAuthedRouteChildren {
  AdminAuthedOnboardRoute: typeof AdminAuthedOnboardRoute
  AdminAuthedSettingsRoute: typeof AdminAuthedSettingsRoute
  AdminAuthedSubscriptionsRoute: typeof AdminAuthedSubscriptionsRoute
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedOnboardRoute: AdminAuthedOnboardRoute,
  AdminAuthedSettingsRoute: AdminAuthedSettingsRoute,
  AdminAuthedSubscriptionsRoute: AdminAuthedSubscriptionsRoute,
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

interface OwnerAuthedRouteChildren {
  OwnerAuthedAnalyticsRoute: typeof OwnerAuthedAnalyticsRoute
  OwnerAuthedMarketingRoute: typeof OwnerAuthedMarketingRoute
  OwnerAuthedMenuRoute: typeof OwnerAuthedMenuRoute
  OwnerAuthedSettingsRoute: typeof OwnerAuthedSettingsRoute
  OwnerAuthedIndexRoute: typeof OwnerAuthedIndexRoute
  OwnerAuthedSettingsWhatsappRoute: typeof OwnerAuthedSettingsWhatsappRoute
}

const OwnerAuthedRouteChildren: OwnerAuthedRouteChildren = {
  OwnerAuthedAnalyticsRoute: OwnerAuthedAnalyticsRoute,
  OwnerAuthedMarketingRoute: OwnerAuthedMarketingRoute,
  OwnerAuthedMenuRoute: OwnerAuthedMenuRoute,
  OwnerAuthedSettingsRoute: OwnerAuthedSettingsRoute,
  OwnerAuthedIndexRoute: OwnerAuthedIndexRoute,
  OwnerAuthedSettingsWhatsappRoute: OwnerAuthedSettingsWhatsappRoute,
}

const OwnerAuthedRouteWithChildren = OwnerAuthedRoute._addFileChildren(
  OwnerAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyReservationsRoute: MyReservationsRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  OwnerAuthedRoute: OwnerAuthedRouteWithChildren,
  OwnerLoginRoute: OwnerLoginRoute,
  RestaurantsSlugRoute: RestaurantsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
